CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE SCHEMA "i18n";
--> statement-breakpoint
CREATE SCHEMA "tmdb";
--> statement-breakpoint
CREATE SCHEMA "ui";
--> statement-breakpoint
CREATE TYPE "public"."bookmark_status" AS ENUM('active', 'completed');--> statement-breakpoint
CREATE TYPE "public"."bookmark_type" AS ENUM('movie', 'tv_series');--> statement-breakpoint
CREATE TYPE "public"."log_tv_status" AS ENUM('watching', 'completed', 'dropped', 'on_hold');--> statement-breakpoint
CREATE TYPE "public"."playlist_item_type_enum" AS ENUM('movie', 'tv_series');--> statement-breakpoint
CREATE TYPE "public"."playlist_member_role_enum" AS ENUM('viewer', 'editor');--> statement-breakpoint
CREATE TYPE "public"."playlist_visibility_enum" AS ENUM('public', 'private', 'followers');--> statement-breakpoint
CREATE TYPE "public"."reco_status" AS ENUM('active', 'completed', 'deleted');--> statement-breakpoint
CREATE TYPE "public"."reco_type" AS ENUM('movie', 'tv_series');--> statement-breakpoint
CREATE TYPE "public"."follow_status_enum" AS ENUM('pending', 'accepted');--> statement-breakpoint
CREATE TYPE "tmdb"."image_type" AS ENUM('backdrop', 'poster', 'logo', 'profile');--> statement-breakpoint
CREATE TABLE "auth"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" uuid NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" uuid NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "auth"."user" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"username" text NOT NULL,
	"display_username" text,
	"username_updated_at" timestamp,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "auth"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bookmark" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "bookmark_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"status" "bookmark_status" DEFAULT 'active' NOT NULL,
	"comment" text,
	"type" "bookmark_type" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	CONSTRAINT "check_user_bookmark_comment" CHECK (length(comment) <= 180),
	CONSTRAINT "check_bookmark_type_references" CHECK ((
        (type = 'movie'::bookmark_type AND movie_id IS NOT NULL AND tv_series_id IS NULL)
        OR
        (type = 'tv_series'::bookmark_type AND tv_series_id IS NOT NULL AND movie_id IS NULL)
      ))
);
--> statement-breakpoint
CREATE TABLE "i18n"."countries" (
	"iso_3166_1" char(2) PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "i18n"."default_countries" (
	"iso_639_1" char(2) PRIMARY KEY NOT NULL,
	"iso_3166_1" char(2) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "i18n"."languages" (
	"iso_639_1" char(2) PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "i18n"."supported_languages" (
	"iso_639_1" char(2) NOT NULL,
	"iso_3166_1" char(2) NOT NULL,
	"language" text PRIMARY KEY GENERATED ALWAYS AS (iso_639_1 || '-' || iso_3166_1) STORED NOT NULL
);
--> statement-breakpoint
CREATE TABLE "log_movie" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_movie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"is_liked" boolean DEFAULT false NOT NULL,
	"liked_at" timestamp with time zone,
	"rating" real,
	"rated_at" timestamp with time zone,
	"watch_count" integer DEFAULT 1 NOT NULL,
	"first_watched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_watched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_log_movie" UNIQUE("movie_id","user_id"),
	CONSTRAINT "check_log_movie_rating" CHECK (
		("log_movie"."rating" >= 0.5) AND 
		("log_movie"."rating" <= 10) AND 
		(("log_movie"."rating" * 2) = FLOOR("log_movie"."rating" * 2))
	)
);
--> statement-breakpoint
CREATE TABLE "log_movie_watched_date" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_movie_watched_date_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"log_movie_id" bigint NOT NULL,
	"watched_date" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "log_tv_series" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_tv_series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"is_liked" boolean DEFAULT false NOT NULL,
	"liked_at" timestamp with time zone,
	"rating" real,
	"rated_at" timestamp with time zone,
	"status" "log_tv_status" DEFAULT 'watching' NOT NULL,
	"watch_count" integer DEFAULT 0 NOT NULL,
	"last_watched_at" timestamp with time zone,
	"last_season_seen" integer,
	"last_episode_seen" integer,
	CONSTRAINT "unique_log_tv_series" UNIQUE("tv_series_id","user_id"),
	CONSTRAINT "check_log_tv_series_rating" CHECK (
		("log_tv_series"."rating" >= 0.5) AND 
		("log_tv_series"."rating" <= 10) AND 
		(("log_tv_series"."rating" * 2) = FLOOR("log_tv_series"."rating" * 2))
	)
);
--> statement-breakpoint
CREATE TABLE "playlist" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"poster" text,
	"visibility" "playlist_visibility_enum" DEFAULT 'public' NOT NULL,
	"items_count" bigint DEFAULT 0 NOT NULL,
	"saved_count" bigint DEFAULT 0 NOT NULL,
	"likes_count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "check_playlist_description_check" CHECK (((description IS NULL) OR ((length(description) >= 1) AND (length(description) <= 300))) AND ((description IS NULL) OR (description !~ '.*
s*
.*'::text)) AND ((description IS NULL) OR (TRIM(BOTH FROM description) <> ''::text))),
	CONSTRAINT "check_playlist_items_count_check" CHECK (items_count >= 0),
	CONSTRAINT "check_playlist_likes_count_check" CHECK (likes_count >= 0),
	CONSTRAINT "check_playlist_saved_count_check" CHECK (saved_count >= 0),
	CONSTRAINT "playlists_title_check" CHECK ((length(title) >= 1) AND (length(title) <= 100))
);
--> statement-breakpoint
CREATE TABLE "playlist_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playlist_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"playlist_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"comment" text,
	"rank" integer NOT NULL,
	"type" "playlist_item_type_enum" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	CONSTRAINT "check_playlist_item_comment" CHECK (length(comment) <= 180),
	CONSTRAINT "check_playlist_item_rank" CHECK (rank >= 1),
	CONSTRAINT "check_playlist_item_type_references" CHECK ((
		(type = 'movie'::playlist_item_type_enum AND movie_id IS NOT NULL AND tv_series_id IS NULL)
		OR
		(type = 'tv_series'::playlist_item_type_enum AND tv_series_id IS NOT NULL AND movie_id IS NULL)
	  ))
);
--> statement-breakpoint
CREATE TABLE "playlist_like" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playlist_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"playlist_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "unique_playlist_like_playlist_user" UNIQUE("playlist_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "playlist_member" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playlist_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"playlist_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"role" "playlist_member_role_enum" DEFAULT 'viewer' NOT NULL,
	CONSTRAINT "unique_playlist_member_playlist_user" UNIQUE("playlist_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "playlist_saved" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playlist_saved_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"playlist_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "unique_playlist_saved_playlist_user" UNIQUE("playlist_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "reco" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "reco_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"sender_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"status" "reco_status" DEFAULT 'active' NOT NULL,
	"comment" text,
	"type" "reco_type" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	CONSTRAINT "check_user_reco_comment" CHECK (length(comment) <= 180),
	CONSTRAINT "check_reco_type_references" CHECK ((
        (type = 'movie'::reco_type AND movie_id IS NOT NULL AND tv_series_id IS NULL)
        OR
        (type = 'tv_series'::reco_type AND tv_series_id IS NOT NULL AND movie_id IS NULL)
      ))
);
--> statement-breakpoint
CREATE TABLE "review_movie" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"title" text,
	"body" text NOT NULL,
	"is_spoiler" boolean DEFAULT false NOT NULL,
	"likes_count" bigint DEFAULT 0 NOT NULL,
	"views_count" bigint DEFAULT 0 NOT NULL,
	"comments_count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "check_review_movie_title" CHECK ((title IS NULL) OR ((length(title) >= 1) AND (length(title) <= 100))),
	CONSTRAINT "check_review_movie_body_html_wrapper" CHECK (body ~ '^<html>.*</html>$'::text)
);
--> statement-breakpoint
CREATE TABLE "review_movie_like" (
	"review_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "review_movie_like_review_id_user_id_pk" PRIMARY KEY("review_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "review_tv_series" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"title" text,
	"body" text NOT NULL,
	"is_spoiler" boolean DEFAULT false NOT NULL,
	"likes_count" bigint DEFAULT 0 NOT NULL,
	"views_count" bigint DEFAULT 0 NOT NULL,
	"comments_count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "check_review_tv_series_title" CHECK ((title IS NULL) OR ((length(title) >= 1) AND (length(title) <= 100))),
	CONSTRAINT "check_review_tv_series_body_html_wrapper" CHECK (body ~ '^<html>.*</html>$'::text)
);
--> statement-breakpoint
CREATE TABLE "review_tv_series_like" (
	"review_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "review_tv_series_like_review_id_user_id_pk" PRIMARY KEY("review_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "follow" (
	"follower_id" uuid NOT NULL,
	"following_id" uuid NOT NULL,
	"status" "follow_status_enum" DEFAULT 'accepted' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "follow_follower_id_following_id_pk" PRIMARY KEY("follower_id","following_id"),
	CONSTRAINT "check_follow_not_self" CHECK ("follow"."follower_id" <> "follow"."following_id")
);
--> statement-breakpoint
CREATE TABLE "follow_person" (
	"user_id" uuid NOT NULL,
	"person_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "follow_person_user_id_person_id_pk" PRIMARY KEY("user_id","person_id")
);
--> statement-breakpoint
CREATE TABLE "profile" (
	"id" uuid PRIMARY KEY NOT NULL,
	"bio" text,
	"background_image" text,
	"language" text DEFAULT 'fr-FR' NOT NULL,
	"is_premium" boolean DEFAULT false NOT NULL,
	"is_private" boolean DEFAULT false NOT NULL,
	"followers_count" bigint DEFAULT 0 NOT NULL,
	"following_count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "check_profile_followers_count" CHECK ("profile"."followers_count" >= 0),
	CONSTRAINT "check_profile_following_count" CHECK ("profile"."following_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE "subscription" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"product_id" text NOT NULL,
	"store" text NOT NULL,
	"status" text NOT NULL,
	"purchased_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone,
	"original_transaction_id" text NOT NULL,
	"transaction_id" text,
	"environment" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."collection" (
	"id" bigint PRIMARY KEY NOT NULL,
	"name" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."collection_image" (
	"id" bigint,
	"collection_id" bigint NOT NULL,
	"file_path" text NOT NULL,
	"type" "tmdb"."image_type" NOT NULL,
	"aspect_ratio" real,
	"height" integer,
	"width" integer,
	"vote_average" real,
	"vote_count" integer,
	"iso_639_1" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."collection_translation" (
	"id" bigint,
	"collection_id" bigint NOT NULL,
	"iso_639_1" text NOT NULL,
	"overview" text,
	"title" text,
	"iso_3166_1" text NOT NULL,
	"homepage" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."company" (
	"id" bigint PRIMARY KEY NOT NULL,
	"name" text,
	"description" text,
	"headquarters" text,
	"homepage" text,
	"origin_country" text,
	"parent_company" bigint
);
--> statement-breakpoint
CREATE TABLE "tmdb"."company_alternative_name" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."company_alternative_name_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_id" bigint NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."company_image" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" bigint NOT NULL,
	"file_path" text NOT NULL,
	"file_type" text NOT NULL,
	"aspect_ratio" real,
	"height" integer,
	"width" integer,
	"vote_average" real,
	"vote_count" integer
);
--> statement-breakpoint
CREATE TABLE "tmdb"."country" (
	"iso_3166_1" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."department" (
	"id" bigint PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."department_translation" (
	"department_id" bigint NOT NULL,
	"language" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "department_translation_department_id_language_pk" PRIMARY KEY("department_id","language")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."gender" (
	"id" bigint PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."genre" (
	"id" bigint PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."genre_translation" (
	"genre_id" bigint NOT NULL,
	"language" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "genre_translation_genre_id_language_pk" PRIMARY KEY("genre_id","language")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."job" (
	"id" bigint PRIMARY KEY NOT NULL,
	"department_id" bigint NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."job_translation" (
	"job_id" bigint NOT NULL,
	"language" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "job_translation_job_id_language_pk" PRIMARY KEY("job_id","language")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."keyword" (
	"id" bigint PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."language" (
	"iso_639_1" char(2) PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie" (
	"id" bigint PRIMARY KEY NOT NULL,
	"adult" boolean DEFAULT false NOT NULL,
	"budget" bigint DEFAULT '0' NOT NULL,
	"original_language" text,
	"original_title" text,
	"popularity" real DEFAULT '0' NOT NULL,
	"revenue" bigint DEFAULT '0' NOT NULL,
	"status" text,
	"vote_average" real DEFAULT '0' NOT NULL,
	"vote_count" real DEFAULT '0' NOT NULL,
	"belongs_to_collection" bigint,
	"updated_at" date
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_alternative_title" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_alternative_title_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	"title" text NOT NULL,
	"type" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_credit" (
	"id" char(24) PRIMARY KEY NOT NULL,
	"movie_id" bigint NOT NULL,
	"person_id" bigint NOT NULL,
	"department" text NOT NULL,
	"job" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_external_id" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_external_id_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"source" text NOT NULL,
	"value" text NOT NULL,
	CONSTRAINT "unique_movie_external_id" UNIQUE("movie_id","source")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_genre" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_genre_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"genre_id" bigint NOT NULL,
	CONSTRAINT "unique_movie_genre" UNIQUE("movie_id","genre_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_image" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"file_path" text NOT NULL,
	"type" "tmdb"."image_type" NOT NULL,
	"aspect_ratio" real DEFAULT '0' NOT NULL,
	"height" integer DEFAULT 0 NOT NULL,
	"width" integer DEFAULT 0 NOT NULL,
	"vote_average" real DEFAULT '0' NOT NULL,
	"vote_count" integer DEFAULT 0 NOT NULL,
	"iso_639_1" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_keyword" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_keyword_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"keyword_id" bigint NOT NULL,
	CONSTRAINT "unique_movie_keyword" UNIQUE("movie_id","keyword_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_origin_country" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_origin_country_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_movie_origin_country" UNIQUE("movie_id","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_production_company" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_production_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"company_id" bigint NOT NULL,
	CONSTRAINT "unique_movie_production_company" UNIQUE("movie_id","company_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_production_country" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_production_country_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_movie_production_country" UNIQUE("movie_id","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_release_date" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_release_date_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	"release_date" timestamp with time zone NOT NULL,
	"certification" text,
	"iso_639_1" text,
	"note" text,
	"release_type" smallint NOT NULL,
	"descriptors" text[]
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_role" (
	"credit_id" char(24) NOT NULL,
	"character" text,
	"order" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_spoken_language" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_spoken_language_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"iso_639_1" text NOT NULL,
	CONSTRAINT "unique_movie_spoken_language" UNIQUE("movie_id","iso_639_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_translation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."movie_translation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"movie_id" bigint NOT NULL,
	"overview" text,
	"tagline" text,
	"title" text,
	"homepage" text,
	"runtime" integer DEFAULT 0 NOT NULL,
	"iso_639_1" text NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_movie_translation" UNIQUE("movie_id","iso_639_1","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."movie_video" (
	"id" char(24) PRIMARY KEY NOT NULL,
	"movie_id" bigint NOT NULL,
	"iso_639_1" text,
	"iso_3166_1" text,
	"name" text,
	"key" text NOT NULL,
	"site" text NOT NULL,
	"size" smallint,
	"type" text,
	"official" boolean NOT NULL,
	"published_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."network" (
	"id" bigint PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"headquarters" text,
	"homepage" text,
	"origin_country" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."network_alternative_name" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."network_alternative_name_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"network_id" bigint NOT NULL,
	"name" text NOT NULL,
	"type" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."network_image" (
	"id" text PRIMARY KEY NOT NULL,
	"network_id" bigint NOT NULL,
	"file_path" text NOT NULL,
	"file_type" text NOT NULL,
	"aspect_ratio" real,
	"height" integer,
	"width" integer,
	"vote_average" real,
	"vote_count" integer
);
--> statement-breakpoint
CREATE TABLE "tmdb"."person" (
	"id" bigint PRIMARY KEY NOT NULL,
	"adult" boolean DEFAULT false NOT NULL,
	"birthday" date,
	"deathday" date,
	"gender" bigint,
	"homepage" text,
	"imdb_id" text,
	"known_for_department" text,
	"name" text,
	"place_of_birth" text,
	"popularity" real
);
--> statement-breakpoint
CREATE TABLE "tmdb"."person_also_known_as" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."person_also_known_as_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"person_id" bigint NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."person_external_id" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."person_external_id_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"person_id" bigint NOT NULL,
	"source" text NOT NULL,
	"value" text NOT NULL,
	CONSTRAINT "unique_person_external_id" UNIQUE("person_id","source")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."person_image" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."person_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"person_id" bigint NOT NULL,
	"file_path" text NOT NULL,
	"aspect_ratio" real,
	"height" integer,
	"width" integer,
	"vote_average" real,
	"vote_count" integer
);
--> statement-breakpoint
CREATE TABLE "tmdb"."person_translation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."person_translation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"person_id" bigint NOT NULL,
	"biography" text,
	"iso_639_1" text NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_person_language_country" UNIQUE("person_id","iso_639_1","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series" (
	"id" bigint PRIMARY KEY NOT NULL,
	"adult" boolean DEFAULT false NOT NULL,
	"in_production" boolean DEFAULT false NOT NULL,
	"original_language" text,
	"original_name" text,
	"popularity" real DEFAULT '0' NOT NULL,
	"status" text,
	"type" text,
	"vote_average" real DEFAULT '0' NOT NULL,
	"vote_count" real DEFAULT '0' NOT NULL,
	"number_of_episodes" integer,
	"number_of_seasons" integer,
	"first_air_date" date,
	"last_air_date" date
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_alternative_title" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_alternative_title_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	"title" text NOT NULL,
	"type" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_content_rating" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_content_rating_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	"rating" text NOT NULL,
	"descriptors" text[]
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_credit" (
	"id" text PRIMARY KEY NOT NULL,
	"tv_series_id" bigint NOT NULL,
	"person_id" bigint NOT NULL,
	"department" text NOT NULL,
	"job" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_external_id" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."tv_series_external_id_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"source" text NOT NULL,
	"value" text NOT NULL,
	CONSTRAINT "unique_tv_series_external_id" UNIQUE("tv_series_id","source")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_genre" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_genre_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"genre_id" bigint NOT NULL,
	CONSTRAINT "unique_tv_series_genre" UNIQUE("tv_series_id","genre_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_image" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"file_path" text NOT NULL,
	"type" "tmdb"."image_type" NOT NULL,
	"aspect_ratio" real DEFAULT '0' NOT NULL,
	"height" integer DEFAULT 0 NOT NULL,
	"width" integer DEFAULT 0 NOT NULL,
	"vote_average" real DEFAULT '0' NOT NULL,
	"vote_count" integer DEFAULT 0 NOT NULL,
	"iso_639_1" text
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_keyword" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_keyword_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"keyword_id" bigint NOT NULL,
	CONSTRAINT "unique_tv_series_keyword" UNIQUE("tv_series_id","keyword_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_language" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_language_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"iso_639_1" text NOT NULL,
	CONSTRAINT "unique_tv_series_language" UNIQUE("tv_series_id","iso_639_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_network" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_network_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"network_id" bigint NOT NULL,
	CONSTRAINT "unique_tv_series_network" UNIQUE("tv_series_id","network_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_origin_country" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_origin_country_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_tv_series_origin_country" UNIQUE("tv_series_id","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_production_company" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_production_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"company_id" bigint NOT NULL,
	CONSTRAINT "unique_tv_series_production_company" UNIQUE("tv_series_id","company_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_production_country" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_production_country_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_tv_series_production_country" UNIQUE("tv_series_id","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_role" (
	"credit_id" text PRIMARY KEY NOT NULL,
	"character" text,
	"episode_count" integer,
	"order" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_spoken_language" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tmdb"."tv_series_spoken_language_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"iso_639_1" text NOT NULL,
	CONSTRAINT "unique_tv_series_spoken_language" UNIQUE("tv_series_id","iso_639_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_translation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."tv_series_translation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_series_id" bigint NOT NULL,
	"name" text,
	"overview" text,
	"homepage" text,
	"tagline" text,
	"iso_639_1" text NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_tv_series_translation" UNIQUE("tv_series_id","iso_639_1","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_series_video" (
	"id" char(24) PRIMARY KEY NOT NULL,
	"tv_series_id" bigint NOT NULL,
	"iso_639_1" text,
	"iso_3166_1" text,
	"name" text,
	"key" text NOT NULL,
	"site" text NOT NULL,
	"size" smallint,
	"type" text,
	"official" boolean DEFAULT false NOT NULL,
	"published_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_season" (
	"id" bigint PRIMARY KEY NOT NULL,
	"tv_series_id" bigint NOT NULL,
	"season_number" integer NOT NULL,
	"vote_average" real NOT NULL,
	"vote_count" integer NOT NULL,
	"poster_path" text,
	CONSTRAINT "unique_tv_season" UNIQUE("tv_series_id","season_number")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_season_credit" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."tv_season_credit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"credit_id" text NOT NULL,
	"tv_season_id" bigint NOT NULL,
	"order" integer,
	CONSTRAINT "unique_tv_season_credit" UNIQUE("credit_id","tv_season_id")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_season_translation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."tv_season_translation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tv_season_id" bigint NOT NULL,
	"name" text,
	"overview" text,
	"iso_639_1" text NOT NULL,
	"iso_3166_1" text NOT NULL,
	CONSTRAINT "unique_tv_season_translation" UNIQUE("tv_season_id","iso_639_1","iso_3166_1")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_episode" (
	"id" bigint PRIMARY KEY NOT NULL,
	"tv_season_id" bigint NOT NULL,
	"air_date" timestamp with time zone,
	"episode_number" integer NOT NULL,
	"episode_type" text,
	"name" text,
	"overview" text,
	"production_code" text,
	"runtime" integer DEFAULT 0,
	"still_path" text,
	"vote_average" real DEFAULT '0' NOT NULL,
	"vote_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "unique_tv_episodes" UNIQUE("tv_season_id","episode_number")
);
--> statement-breakpoint
CREATE TABLE "tmdb"."tv_episode_credit" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."tv_episode_credit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"credit_id" text NOT NULL,
	"tv_episode_id" bigint NOT NULL,
	CONSTRAINT "unique_tv_episode_credit" UNIQUE("credit_id","tv_episode_id")
);
--> statement-breakpoint
ALTER TABLE "auth"."account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmark" ADD CONSTRAINT "bookmark_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmark" ADD CONSTRAINT "bookmark_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmark" ADD CONSTRAINT "bookmark_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "i18n"."default_countries" ADD CONSTRAINT "default_countries_iso_639_1_languages_iso_639_1_fk" FOREIGN KEY ("iso_639_1") REFERENCES "i18n"."languages"("iso_639_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "i18n"."default_countries" ADD CONSTRAINT "default_countries_iso_3166_1_countries_iso_3166_1_fk" FOREIGN KEY ("iso_3166_1") REFERENCES "i18n"."countries"("iso_3166_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "i18n"."supported_languages" ADD CONSTRAINT "supported_languages_iso_639_1_languages_iso_639_1_fk" FOREIGN KEY ("iso_639_1") REFERENCES "i18n"."languages"("iso_639_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "i18n"."supported_languages" ADD CONSTRAINT "supported_languages_iso_3166_1_countries_iso_3166_1_fk" FOREIGN KEY ("iso_3166_1") REFERENCES "i18n"."countries"("iso_3166_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_movie" ADD CONSTRAINT "log_movie_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_movie" ADD CONSTRAINT "log_movie_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_movie_watched_date" ADD CONSTRAINT "log_movie_watched_date_log_movie_id_log_movie_id_fk" FOREIGN KEY ("log_movie_id") REFERENCES "public"."log_movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_tv_series" ADD CONSTRAINT "log_tv_series_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_tv_series" ADD CONSTRAINT "log_tv_series_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist" ADD CONSTRAINT "playlist_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_item" ADD CONSTRAINT "playlist_item_playlist_id_playlist_id_fk" FOREIGN KEY ("playlist_id") REFERENCES "public"."playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_item" ADD CONSTRAINT "playlist_item_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_item" ADD CONSTRAINT "playlist_item_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_item" ADD CONSTRAINT "playlist_item_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_like" ADD CONSTRAINT "playlist_like_playlist_id_playlist_id_fk" FOREIGN KEY ("playlist_id") REFERENCES "public"."playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_like" ADD CONSTRAINT "playlist_like_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_member" ADD CONSTRAINT "playlist_member_playlist_id_playlist_id_fk" FOREIGN KEY ("playlist_id") REFERENCES "public"."playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_member" ADD CONSTRAINT "playlist_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_saved" ADD CONSTRAINT "playlist_saved_playlist_id_playlist_id_fk" FOREIGN KEY ("playlist_id") REFERENCES "public"."playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playlist_saved" ADD CONSTRAINT "playlist_saved_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reco" ADD CONSTRAINT "reco_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reco" ADD CONSTRAINT "reco_sender_id_user_id_fk" FOREIGN KEY ("sender_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reco" ADD CONSTRAINT "reco_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reco" ADD CONSTRAINT "reco_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie" ADD CONSTRAINT "review_movie_id_log_movie_id_fk" FOREIGN KEY ("id") REFERENCES "public"."log_movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie_like" ADD CONSTRAINT "review_movie_like_review_id_review_movie_id_fk" FOREIGN KEY ("review_id") REFERENCES "public"."review_movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie_like" ADD CONSTRAINT "review_movie_like_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series" ADD CONSTRAINT "review_tv_series_id_log_tv_series_id_fk" FOREIGN KEY ("id") REFERENCES "public"."log_tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_like" ADD CONSTRAINT "review_tv_series_like_review_id_review_tv_series_id_fk" FOREIGN KEY ("review_id") REFERENCES "public"."review_tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_like" ADD CONSTRAINT "review_tv_series_like_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follow" ADD CONSTRAINT "follow_follower_id_user_id_fk" FOREIGN KEY ("follower_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follow" ADD CONSTRAINT "follow_following_id_user_id_fk" FOREIGN KEY ("following_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follow_person" ADD CONSTRAINT "follow_person_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follow_person" ADD CONSTRAINT "follow_person_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile" ADD CONSTRAINT "profile_id_user_id_fk" FOREIGN KEY ("id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscription" ADD CONSTRAINT "subscription_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."collection_image" ADD CONSTRAINT "collection_image_collection_id_collection_id_fk" FOREIGN KEY ("collection_id") REFERENCES "tmdb"."collection"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."collection_translation" ADD CONSTRAINT "collection_translation_collection_id_collection_id_fk" FOREIGN KEY ("collection_id") REFERENCES "tmdb"."collection"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."company" ADD CONSTRAINT "company_parent_company_company_id_fk" FOREIGN KEY ("parent_company") REFERENCES "tmdb"."company"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tmdb"."company_alternative_name" ADD CONSTRAINT "company_alternative_name_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "tmdb"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."company_image" ADD CONSTRAINT "company_image_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "tmdb"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."department_translation" ADD CONSTRAINT "department_translation_department_id_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "tmdb"."department"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."genre_translation" ADD CONSTRAINT "genre_translation_genre_id_genre_id_fk" FOREIGN KEY ("genre_id") REFERENCES "tmdb"."genre"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."job" ADD CONSTRAINT "job_department_id_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "tmdb"."department"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."job_translation" ADD CONSTRAINT "job_translation_job_id_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "tmdb"."job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie" ADD CONSTRAINT "movie_belongs_to_collection_collection_id_fk" FOREIGN KEY ("belongs_to_collection") REFERENCES "tmdb"."collection"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_alternative_title" ADD CONSTRAINT "movie_alternative_title_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_credit" ADD CONSTRAINT "movie_credit_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_credit" ADD CONSTRAINT "movie_credit_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_external_id" ADD CONSTRAINT "movie_external_id_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_genre" ADD CONSTRAINT "movie_genre_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_genre" ADD CONSTRAINT "movie_genre_genre_id_genre_id_fk" FOREIGN KEY ("genre_id") REFERENCES "tmdb"."genre"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_image" ADD CONSTRAINT "movie_image_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_keyword" ADD CONSTRAINT "movie_keyword_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_keyword" ADD CONSTRAINT "movie_keyword_keyword_id_keyword_id_fk" FOREIGN KEY ("keyword_id") REFERENCES "tmdb"."keyword"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_origin_country" ADD CONSTRAINT "movie_origin_country_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_origin_country" ADD CONSTRAINT "movie_origin_country_iso_3166_1_country_iso_3166_1_fk" FOREIGN KEY ("iso_3166_1") REFERENCES "tmdb"."country"("iso_3166_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_production_company" ADD CONSTRAINT "movie_production_company_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_production_company" ADD CONSTRAINT "movie_production_company_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "tmdb"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_production_country" ADD CONSTRAINT "movie_production_country_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_production_country" ADD CONSTRAINT "movie_production_country_iso_3166_1_country_iso_3166_1_fk" FOREIGN KEY ("iso_3166_1") REFERENCES "tmdb"."country"("iso_3166_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_release_date" ADD CONSTRAINT "movie_release_date_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_release_date" ADD CONSTRAINT "movie_release_date_iso_3166_1_country_iso_3166_1_fk" FOREIGN KEY ("iso_3166_1") REFERENCES "tmdb"."country"("iso_3166_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_release_date" ADD CONSTRAINT "movie_release_date_iso_639_1_language_iso_639_1_fk" FOREIGN KEY ("iso_639_1") REFERENCES "tmdb"."language"("iso_639_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_role" ADD CONSTRAINT "movie_role_credit_id_movie_credit_id_fk" FOREIGN KEY ("credit_id") REFERENCES "tmdb"."movie_credit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_spoken_language" ADD CONSTRAINT "movie_spoken_language_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_spoken_language" ADD CONSTRAINT "movie_spoken_language_iso_639_1_language_iso_639_1_fk" FOREIGN KEY ("iso_639_1") REFERENCES "tmdb"."language"("iso_639_1") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_translation" ADD CONSTRAINT "movie_translation_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."movie_video" ADD CONSTRAINT "movie_video_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."network_alternative_name" ADD CONSTRAINT "network_alternative_name_network_id_network_id_fk" FOREIGN KEY ("network_id") REFERENCES "tmdb"."network"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."network_image" ADD CONSTRAINT "network_image_network_id_network_id_fk" FOREIGN KEY ("network_id") REFERENCES "tmdb"."network"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."person" ADD CONSTRAINT "person_gender_gender_id_fk" FOREIGN KEY ("gender") REFERENCES "tmdb"."gender"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."person_also_known_as" ADD CONSTRAINT "person_also_known_as_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."person_external_id" ADD CONSTRAINT "person_external_id_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."person_image" ADD CONSTRAINT "person_image_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."person_translation" ADD CONSTRAINT "person_translation_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_alternative_title" ADD CONSTRAINT "tv_series_alternative_title_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_content_rating" ADD CONSTRAINT "tv_series_content_rating_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_credit" ADD CONSTRAINT "tv_series_credit_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_credit" ADD CONSTRAINT "tv_series_credit_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_external_id" ADD CONSTRAINT "tv_series_external_id_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_genre" ADD CONSTRAINT "tv_series_genre_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_genre" ADD CONSTRAINT "tv_series_genre_genre_id_genre_id_fk" FOREIGN KEY ("genre_id") REFERENCES "tmdb"."genre"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_image" ADD CONSTRAINT "tv_series_image_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_keyword" ADD CONSTRAINT "tv_series_keyword_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_keyword" ADD CONSTRAINT "tv_series_keyword_keyword_id_keyword_id_fk" FOREIGN KEY ("keyword_id") REFERENCES "tmdb"."keyword"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_language" ADD CONSTRAINT "tv_series_language_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_network" ADD CONSTRAINT "tv_series_network_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_network" ADD CONSTRAINT "tv_series_network_network_id_network_id_fk" FOREIGN KEY ("network_id") REFERENCES "tmdb"."network"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_origin_country" ADD CONSTRAINT "tv_series_origin_country_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_production_company" ADD CONSTRAINT "tv_series_production_company_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_production_company" ADD CONSTRAINT "tv_series_production_company_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "tmdb"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_production_country" ADD CONSTRAINT "tv_series_production_country_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_role" ADD CONSTRAINT "tv_series_role_credit_id_tv_series_credit_id_fk" FOREIGN KEY ("credit_id") REFERENCES "tmdb"."tv_series_credit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_spoken_language" ADD CONSTRAINT "tv_series_spoken_language_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_translation" ADD CONSTRAINT "tv_series_translation_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_series_video" ADD CONSTRAINT "tv_series_video_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_season" ADD CONSTRAINT "tv_season_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_season_credit" ADD CONSTRAINT "tv_season_credit_credit_id_tv_series_credit_id_fk" FOREIGN KEY ("credit_id") REFERENCES "tmdb"."tv_series_credit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_season_credit" ADD CONSTRAINT "tv_season_credit_tv_season_id_tv_season_id_fk" FOREIGN KEY ("tv_season_id") REFERENCES "tmdb"."tv_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_season_translation" ADD CONSTRAINT "tv_season_translation_tv_season_id_tv_season_id_fk" FOREIGN KEY ("tv_season_id") REFERENCES "tmdb"."tv_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_episode" ADD CONSTRAINT "tv_episode_tv_season_id_tv_season_id_fk" FOREIGN KEY ("tv_season_id") REFERENCES "tmdb"."tv_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_episode_credit" ADD CONSTRAINT "tv_episode_credit_credit_id_tv_series_credit_id_fk" FOREIGN KEY ("credit_id") REFERENCES "tmdb"."tv_series_credit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmdb"."tv_episode_credit" ADD CONSTRAINT "tv_episode_credit_tv_episode_id_tv_episode_id_fk" FOREIGN KEY ("tv_episode_id") REFERENCES "tmdb"."tv_episode"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "auth"."account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "auth"."session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "auth"."verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "idx_bookmark_user_id" ON "bookmark" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_bookmark_status" ON "bookmark" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active_bookmark" ON "bookmark" USING btree ("user_id","type","movie_id","tv_series_id") WHERE "bookmark"."status" = 'active'::bookmark_status;--> statement-breakpoint
CREATE INDEX "idx_log_movie_movie_id" ON "log_movie" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_log_movie_user_id" ON "log_movie" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_log_movie_rating" ON "log_movie" USING btree ("rating");--> statement-breakpoint
CREATE INDEX "idx_log_movie_is_liked" ON "log_movie" USING btree ("is_liked");--> statement-breakpoint
CREATE INDEX "idx_log_movie_watched_date_log_movie_id" ON "log_movie_watched_date" USING btree ("log_movie_id");--> statement-breakpoint
CREATE INDEX "idx_log_movie_watched_date_watched_date" ON "log_movie_watched_date" USING btree ("watched_date");--> statement-breakpoint
CREATE INDEX "idx_log_tv_series_tv_series_id" ON "log_tv_series" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_series_user_id" ON "log_tv_series" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_series_rating" ON "log_tv_series" USING btree ("rating");--> statement-breakpoint
CREATE INDEX "idx_log_tv_series_is_liked" ON "log_tv_series" USING btree ("is_liked");--> statement-breakpoint
CREATE INDEX "idx_log_tv_series_status" ON "log_tv_series" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_playlist_created_at" ON "playlist" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_playlist_visibility" ON "playlist" USING btree ("visibility");--> statement-breakpoint
CREATE INDEX "idx_playlist_items_count" ON "playlist" USING btree ("items_count");--> statement-breakpoint
CREATE INDEX "idx_playlist_likes_count" ON "playlist" USING btree ("likes_count");--> statement-breakpoint
CREATE INDEX "idx_playlist_saved_count" ON "playlist" USING btree ("saved_count");--> statement-breakpoint
CREATE INDEX "idx_playlist_user_id" ON "playlist" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_playlist_item_playlist_id" ON "playlist_item" USING btree ("playlist_id");--> statement-breakpoint
CREATE INDEX "idx_playlist_item_user_id" ON "playlist_item" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_playlist_item_rank" ON "playlist_item" USING btree ("rank");--> statement-breakpoint
CREATE INDEX "idx_playlist_like_playlist_id" ON "playlist_like" USING btree ("playlist_id");--> statement-breakpoint
CREATE INDEX "idx_playlist_like_user_id" ON "playlist_like" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "playlist_member_playlist_id" ON "playlist_member" USING btree ("playlist_id");--> statement-breakpoint
CREATE INDEX "playlist_member_user_id" ON "playlist_member" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_playlist_saved_playlist_id" ON "playlist_saved" USING btree ("playlist_id");--> statement-breakpoint
CREATE INDEX "idx_playlist_saved_user_id" ON "playlist_saved" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_reco_user_id" ON "reco" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_reco_sender_id" ON "reco" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "idx_reco_status" ON "reco" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active_reco" ON "reco" USING btree ("user_id","sender_id","type","movie_id","tv_series_id") WHERE "reco"."status" = 'active'::reco_status;--> statement-breakpoint
CREATE INDEX "idx_review_movie_created_at" ON "review_movie" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_review_movie_likes_count" ON "review_movie" USING btree ("likes_count");--> statement-breakpoint
CREATE INDEX "idx_review_movie_views_count" ON "review_movie" USING btree ("views_count");--> statement-breakpoint
CREATE INDEX "idx_review_movie_comments_count" ON "review_movie" USING btree ("comments_count");--> statement-breakpoint
CREATE INDEX "idx_review_movie_like_user_id" ON "review_movie_like" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_created_at" ON "review_tv_series" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_likes_count" ON "review_tv_series" USING btree ("likes_count");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_views_count" ON "review_tv_series" USING btree ("views_count");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comments_count" ON "review_tv_series" USING btree ("comments_count");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_like_user_id" ON "review_tv_series_like" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_follow_person_user_id" ON "follow_person" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_follow_person_person_id" ON "follow_person" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_subscription_original_transaction_id" ON "subscription" USING btree ("original_transaction_id");--> statement-breakpoint
CREATE INDEX "idx_subscription_product_id" ON "subscription" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "idx_subscription_status" ON "subscription" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_subscription_user_id" ON "subscription" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_image_collection_id" ON "tmdb"."collection_image" USING btree ("collection_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_image_iso_language" ON "tmdb"."collection_image" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_image_type" ON "tmdb"."collection_image" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_image_vote_average" ON "tmdb"."collection_image" USING btree ("vote_average");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_translation_collection_id" ON "tmdb"."collection_translation" USING btree ("collection_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_translation_collection_language" ON "tmdb"."collection_translation" USING btree ("collection_id","iso_639_1","iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_translation_iso_3166_1" ON "tmdb"."collection_translation" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_collection_translation_iso_639_1" ON "tmdb"."collection_translation" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_company_alternative_name_company_id" ON "tmdb"."company_alternative_name" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_company_image_company_id" ON "tmdb"."company_image" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_company_image_vote_average" ON "tmdb"."company_image" USING btree ("vote_average");--> statement-breakpoint
CREATE INDEX "idx_tmdb_department_translation_language" ON "tmdb"."department_translation" USING btree ("language");--> statement-breakpoint
CREATE INDEX "idx_tmdb_job_department_id" ON "tmdb"."job" USING btree ("department_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_job_translation_language" ON "tmdb"."job_translation" USING btree ("language");--> statement-breakpoint
CREATE INDEX "idx_tmdb_keyword_name" ON "tmdb"."keyword" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_popularity" ON "tmdb"."movie" USING btree ("popularity");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_alternative_title_iso_3166_1" ON "tmdb"."movie_alternative_title" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_alternative_title_movie_id" ON "tmdb"."movie_alternative_title" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_credit_job" ON "tmdb"."movie_credit" USING btree ("job");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_credit_movie_id_director" ON "tmdb"."movie_credit" USING btree ("movie_id") WHERE (job = 'Director'::text);--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_credit_department" ON "tmdb"."movie_credit" USING btree ("department");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_credit_movie_id" ON "tmdb"."movie_credit" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_credit_person_id" ON "tmdb"."movie_credit" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_external_id_movie_id" ON "tmdb"."movie_external_id" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_genre_genre_id" ON "tmdb"."movie_genre" USING btree ("genre_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_genre_movie_id" ON "tmdb"."movie_genre" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_image_movie_id" ON "tmdb"."movie_image" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_image_iso_639_1" ON "tmdb"."movie_image" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_image_type" ON "tmdb"."movie_image" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_image_vote_average" ON "tmdb"."movie_image" USING btree ("vote_average");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_keyword_keyword_id" ON "tmdb"."movie_keyword" USING btree ("keyword_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_keyword_movie_id" ON "tmdb"."movie_keyword" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_origin_country_country_id_idx" ON "tmdb"."movie_origin_country" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_origin_country_movie_id_idx" ON "tmdb"."movie_origin_country" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_production_company_id" ON "tmdb"."movie_production_company" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_production_movie_id" ON "tmdb"."movie_production_company" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_country_country_id" ON "tmdb"."movie_production_country" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_country_movie_id" ON "tmdb"."movie_production_country" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_release_date_iso_3166_1" ON "tmdb"."movie_release_date" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_release_date_movie_id" ON "tmdb"."movie_release_date" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_release_date_release_date" ON "tmdb"."movie_release_date" USING btree ("release_date");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_release_date_release_type" ON "tmdb"."movie_release_date" USING btree ("release_type");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_language_language_id" ON "tmdb"."movie_spoken_language" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_language_movie_id" ON "tmdb"."movie_spoken_language" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_translation_movie_id" ON "tmdb"."movie_translation" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_translation_iso_3166_1" ON "tmdb"."movie_translation" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_translation_iso_639_1" ON "tmdb"."movie_translation" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_video_iso_3166_1" ON "tmdb"."movie_video" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_video_iso_639_1" ON "tmdb"."movie_video" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_video_movie_id" ON "tmdb"."movie_video" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_movie_video_type" ON "tmdb"."movie_video" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_tmdb_network_alternative_name_network_id" ON "tmdb"."network_alternative_name" USING btree ("network_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_network_image_network_id" ON "tmdb"."network_image" USING btree ("network_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_network_image_vote_average" ON "tmdb"."network_image" USING btree ("vote_average");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_popularity" ON "tmdb"."person" USING btree ("popularity");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_also_known_as_name" ON "tmdb"."person_also_known_as" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_also_known_as_person_id" ON "tmdb"."person_also_known_as" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_external_id_person_id" ON "tmdb"."person_external_id" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_image_person_id" ON "tmdb"."person_image" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_image_vote_average" ON "tmdb"."person_image" USING btree ("vote_average");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_translation_iso_3166_1" ON "tmdb"."person_translation" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_translation_iso_639_1" ON "tmdb"."person_translation" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_translation_iso_639_1_iso_3166_1" ON "tmdb"."person_translation" USING btree ("iso_639_1","iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_person_translation_person_id" ON "tmdb"."person_translation" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_popularity" ON "tmdb"."tv_series" USING btree ("popularity");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_alternative_title_iso_3166_1" ON "tmdb"."tv_series_alternative_title" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_alternative_title_tv_series_id" ON "tmdb"."tv_series_alternative_title" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_content_rating_iso_3166_1" ON "tmdb"."tv_series_content_rating" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_content_rating_tv_series_id" ON "tmdb"."tv_series_content_rating" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_credit_department" ON "tmdb"."tv_series_credit" USING btree ("department");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_credit_job" ON "tmdb"."tv_series_credit" USING btree ("job");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_credit_person_id" ON "tmdb"."tv_series_credit" USING btree ("person_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_credit_tv_series_id" ON "tmdb"."tv_series_credit" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_credit_tv_series_id_creator" ON "tmdb"."tv_series_credit" USING btree ("tv_series_id") WHERE (job = 'Creator'::text);--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_external_id_tv_series_id" ON "tmdb"."tv_series_external_id" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_genre_genre_id" ON "tmdb"."tv_series_genre" USING btree ("genre_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_genre_tv_series_id" ON "tmdb"."tv_series_genre" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_image_iso_639_1" ON "tmdb"."tv_series_image" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_image_tv_series_id" ON "tmdb"."tv_series_image" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_image_type" ON "tmdb"."tv_series_image" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_image_vote_average" ON "tmdb"."tv_series_image" USING btree ("vote_average");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_keyword_keyword_id" ON "tmdb"."tv_series_keyword" USING btree ("keyword_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_keyword_tv_series_id" ON "tmdb"."tv_series_keyword" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_language_iso_639_1" ON "tmdb"."tv_series_language" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_language_tv_series_id" ON "tmdb"."tv_series_language" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_network_network_id" ON "tmdb"."tv_series_network" USING btree ("network_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_network_tv_series_id" ON "tmdb"."tv_series_network" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_origin_country_iso_3166_1" ON "tmdb"."tv_series_origin_country" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_origin_country_tv_series_id" ON "tmdb"."tv_series_origin_country" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_production_company_company_id" ON "tmdb"."tv_series_production_company" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_production_company_tv_series_id" ON "tmdb"."tv_series_production_company" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_production_country_iso_3166_1" ON "tmdb"."tv_series_production_country" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_production_country_tv_series_id" ON "tmdb"."tv_series_production_country" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_spoken_language_iso_639_1" ON "tmdb"."tv_series_spoken_language" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_spoken_language_tv_series_id" ON "tmdb"."tv_series_spoken_language" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_translation_iso_3166_1" ON "tmdb"."tv_series_translation" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_translation_iso_639_1" ON "tmdb"."tv_series_translation" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_translation_tv_series_id" ON "tmdb"."tv_series_translation" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_video_iso_3166_1" ON "tmdb"."tv_series_video" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_video_iso_639_1" ON "tmdb"."tv_series_video" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_video_tv_series_id" ON "tmdb"."tv_series_video" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_series_video_type" ON "tmdb"."tv_series_video" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_season_number" ON "tmdb"."tv_season" USING btree ("season_number");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_tv_series_id" ON "tmdb"."tv_season" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_credit_credit_id" ON "tmdb"."tv_season_credit" USING btree ("credit_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_credit_tv_season_id" ON "tmdb"."tv_season_credit" USING btree ("tv_season_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_translation_iso_3166_1" ON "tmdb"."tv_season_translation" USING btree ("iso_3166_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_translation_iso_639_1" ON "tmdb"."tv_season_translation" USING btree ("iso_639_1");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_season_translation_tv_season_id" ON "tmdb"."tv_season_translation" USING btree ("tv_season_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_episode_episode_number" ON "tmdb"."tv_episode" USING btree ("episode_number");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_episode_tv_season_id" ON "tmdb"."tv_episode" USING btree ("tv_season_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_episode_credit_credit_id" ON "tmdb"."tv_episode_credit" USING btree ("credit_id");--> statement-breakpoint
CREATE INDEX "idx_tmdb_tv_episode_credit_tv_episode_id" ON "tmdb"."tv_episode_credit" USING btree ("tv_episode_id");