CREATE TYPE "public"."feed_type" AS ENUM('log_movie', 'log_tv_series', 'playlist_like', 'review_movie_like', 'review_tv_series_like');--> statement-breakpoint
CREATE TABLE "feed" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feed_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL,
	"activity_type" "feed_type" NOT NULL,
	"activity_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "feed" ADD CONSTRAINT "feed_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_feed_user_id_created_at_desc" ON "feed" USING btree ("user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "idx_feed_activity_type_activity_id" ON "feed" USING btree ("activity_type","activity_id");