ALTER TABLE "review_movie_like" DROP CONSTRAINT "review_movie_like_review_id_user_id_pk";--> statement-breakpoint
ALTER TABLE "review_tv_series_like" DROP CONSTRAINT "review_tv_series_like_review_id_user_id_pk";--> statement-breakpoint
ALTER TABLE "review_movie_like" ADD COLUMN "id" bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "review_movie_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "review_tv_series_like" ADD COLUMN "id" bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "review_tv_series_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "review_movie_like" ADD CONSTRAINT "unique_review_movie_like" UNIQUE("review_id","user_id");--> statement-breakpoint
ALTER TABLE "review_tv_series_like" ADD CONSTRAINT "unique_review_tv_series_like" UNIQUE("review_id","user_id");