CREATE TABLE "log_tv_episode" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_tv_episode_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"log_tv_series_id" bigint NOT NULL,
	"log_tv_season_id" bigint NOT NULL,
	"tv_episode_id" bigint NOT NULL,
	"season_number" integer NOT NULL,
	"episode_number" integer NOT NULL,
	"watch_count" integer DEFAULT 1 NOT NULL,
	"rating" real,
	"rated_at" timestamp with time zone,
	"first_watched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_watched_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_log_tv_episode" UNIQUE("log_tv_season_id","tv_episode_id"),
	CONSTRAINT "check_log_tv_episode_rating" CHECK (("log_tv_episode"."rating" >= 0.5) AND ("log_tv_episode"."rating" <= 10) AND (("log_tv_episode"."rating" * 2) = FLOOR("log_tv_episode"."rating" * 2)))
);
--> statement-breakpoint
CREATE TABLE "log_tv_season" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_tv_season_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"log_tv_series_id" bigint NOT NULL,
	"tv_season_id" bigint NOT NULL,
	"season_number" integer NOT NULL,
	"status" "log_tv_status" DEFAULT 'watching' NOT NULL,
	"episodes_watched_count" integer DEFAULT 0 NOT NULL,
	"rating" real,
	"rated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "unique_log_tv_season" UNIQUE("log_tv_series_id","tv_season_id"),
	CONSTRAINT "check_log_tv_season_rating" CHECK (("log_tv_season"."rating" >= 0.5) AND ("log_tv_season"."rating" <= 10) AND (("log_tv_season"."rating" * 2) = FLOOR("log_tv_season"."rating" * 2)))
);
--> statement-breakpoint
ALTER TABLE "log_tv_series" DROP CONSTRAINT "check_log_tv_series_rating";--> statement-breakpoint
ALTER TABLE "log_tv_season" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "log_tv_season" ALTER COLUMN "status" SET DEFAULT 'watching'::text;--> statement-breakpoint
ALTER TABLE "log_tv_series" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "log_tv_series" ALTER COLUMN "status" SET DEFAULT 'watching'::text;--> statement-breakpoint
DROP TYPE "public"."log_tv_status";--> statement-breakpoint
CREATE TYPE "public"."log_tv_status" AS ENUM('watching', 'completed', 'dropped');--> statement-breakpoint
ALTER TABLE "log_tv_season" ALTER COLUMN "status" SET DEFAULT 'watching'::"public"."log_tv_status";--> statement-breakpoint
ALTER TABLE "log_tv_season" ALTER COLUMN "status" SET DATA TYPE "public"."log_tv_status" USING "status"::"public"."log_tv_status";--> statement-breakpoint
ALTER TABLE "log_tv_series" ALTER COLUMN "status" SET DEFAULT 'watching'::"public"."log_tv_status";--> statement-breakpoint
ALTER TABLE "log_tv_series" ALTER COLUMN "status" SET DATA TYPE "public"."log_tv_status" USING "status"::"public"."log_tv_status";--> statement-breakpoint
ALTER TABLE "log_tv_series" ADD COLUMN "episodes_watched_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "log_tv_episode" ADD CONSTRAINT "log_tv_episode_log_tv_series_id_log_tv_series_id_fk" FOREIGN KEY ("log_tv_series_id") REFERENCES "public"."log_tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_tv_episode" ADD CONSTRAINT "log_tv_episode_log_tv_season_id_log_tv_season_id_fk" FOREIGN KEY ("log_tv_season_id") REFERENCES "public"."log_tv_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_tv_episode" ADD CONSTRAINT "log_tv_episode_tv_episode_id_tv_episode_id_fk" FOREIGN KEY ("tv_episode_id") REFERENCES "tmdb"."tv_episode"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_tv_season" ADD CONSTRAINT "log_tv_season_log_tv_series_id_log_tv_series_id_fk" FOREIGN KEY ("log_tv_series_id") REFERENCES "public"."log_tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log_tv_season" ADD CONSTRAINT "log_tv_season_tv_season_id_tv_season_id_fk" FOREIGN KEY ("tv_season_id") REFERENCES "tmdb"."tv_season"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_log_tv_episode_log_tv_series_id" ON "log_tv_episode" USING btree ("log_tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_episode_log_tv_season_id" ON "log_tv_episode" USING btree ("log_tv_season_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_episode_tv_episode_id" ON "log_tv_episode" USING btree ("tv_episode_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_episode_rating" ON "log_tv_episode" USING btree ("rating");--> statement-breakpoint
CREATE INDEX "idx_log_tv_season_log_tv_series_id" ON "log_tv_season" USING btree ("log_tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_season_tv_season_id" ON "log_tv_season" USING btree ("tv_season_id");--> statement-breakpoint
CREATE INDEX "idx_log_tv_season_status" ON "log_tv_season" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_log_tv_season_rating" ON "log_tv_season" USING btree ("rating");--> statement-breakpoint
ALTER TABLE "log_tv_series" ADD CONSTRAINT "check_log_tv_series_rating" CHECK (("log_tv_series"."rating" >= 0.5) AND ("log_tv_series"."rating" <= 10) AND (("log_tv_series"."rating" * 2) = FLOOR("log_tv_series"."rating" * 2)));