CREATE TYPE "tmdb"."sync_log_status" AS ENUM('initialized', 'fetching_data', 'data_fetched', 'syncing_to_db', 'updating_popularity', 'success', 'failed');--> statement-breakpoint
CREATE TYPE "tmdb"."sync_log_type" AS ENUM('movie', 'person', 'collection', 'keyword', 'company', 'language', 'country', 'genre', 'network', 'tv_serie');--> statement-breakpoint
CREATE TABLE "tmdb"."sync_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmdb"."sync_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"type" "tmdb"."sync_log_type" NOT NULL,
	"status" "tmdb"."sync_log_status" DEFAULT 'initialized' NOT NULL,
	"date" date DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_sync_logs_type" ON "tmdb"."sync_logs" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_sync_logs_status" ON "tmdb"."sync_logs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_sync_logs_date" ON "tmdb"."sync_logs" USING btree ("date");