CREATE TABLE "playlist_featured" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playlist_featured_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"playlist_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_playlist_featured_playlist_id" UNIQUE("playlist_id")
);
--> statement-breakpoint
ALTER TABLE "playlist_featured" ADD CONSTRAINT "playlist_featured_playlist_id_playlist_id_fk" FOREIGN KEY ("playlist_id") REFERENCES "public"."playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_playlist_featured_created_at" ON "playlist_featured" USING btree ("created_at");