CREATE TYPE "public"."explore_item_type_enum" AS ENUM('movie', 'tv_series');--> statement-breakpoint
CREATE TABLE "explore" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "explore_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	CONSTRAINT "unique_explore_slug" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "explore_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "explore_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"explore_id" bigint NOT NULL,
	"location" geometry(point) NOT NULL,
	"type" "explore_item_type_enum" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	CONSTRAINT "check_explore_item_type_references" CHECK ((
				(type = 'movie'::explore_item_type_enum AND movie_id IS NOT NULL AND tv_series_id IS NULL)
				OR
				(type = 'tv_series'::explore_item_type_enum AND tv_series_id IS NOT NULL AND movie_id IS NULL)
			))
);
--> statement-breakpoint
ALTER TABLE "explore_item" ADD CONSTRAINT "explore_item_explore_id_explore_id_fk" FOREIGN KEY ("explore_id") REFERENCES "public"."explore"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explore_item" ADD CONSTRAINT "explore_item_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "explore_item" ADD CONSTRAINT "explore_item_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_explore_item_explore_id" ON "explore_item" USING btree ("explore_id");--> statement-breakpoint
CREATE INDEX "idx_explore_item_movie_id" ON "explore_item" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_explore_item_tv_series_id" ON "explore_item" USING btree ("tv_series_id");