CREATE TYPE "public"."import_job_bookmark_type" AS ENUM('movie', 'tv_series');--> statement-breakpoint
CREATE TYPE "public"."import_job_direction" AS ENUM('import', 'export');--> statement-breakpoint
CREATE TYPE "public"."import_job_playlist_item_type" AS ENUM('movie', 'tv_series');--> statement-breakpoint
CREATE TYPE "public"."import_job_provider" AS ENUM('letterboxd', 'senscritique', 'recomend');--> statement-breakpoint
CREATE TYPE "public"."import_job_status" AS ENUM('pending', 'processing', 'awaiting_review', 'completed', 'failed');--> statement-breakpoint
CREATE TYPE "public"."import_match_status" AS ENUM('matched', 'unmatched', 'skipped');--> statement-breakpoint
CREATE TYPE "public"."import_resolution" AS ENUM('keep_existing', 'use_imported', 'merge');--> statement-breakpoint
CREATE TABLE "import_job" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"provider" "import_job_provider" NOT NULL,
	"direction" "import_job_direction" NOT NULL,
	"status" "import_job_status" DEFAULT 'pending' NOT NULL,
	"file_key" text,
	"items_total" integer DEFAULT 0 NOT NULL,
	"items_processed" integer DEFAULT 0 NOT NULL,
	"items_matched" integer DEFAULT 0 NOT NULL,
	"items_failed" integer DEFAULT 0 NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_job_bookmark" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_bookmark_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_id" bigint NOT NULL,
	"raw_title" text NOT NULL,
	"raw_year" integer,
	"type" "import_job_bookmark_type" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	"match_status" "import_match_status" DEFAULT 'unmatched' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_job_log_movie" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_log_movie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_id" bigint NOT NULL,
	"raw_title" text NOT NULL,
	"raw_year" integer,
	"movie_id" bigint,
	"match_status" "import_match_status" DEFAULT 'unmatched' NOT NULL,
	"imported_rating" real,
	"imported_is_liked" boolean DEFAULT false NOT NULL,
	"existing_log_movie_id" bigint,
	"existing_rating" real,
	"existing_is_liked" boolean,
	"resolution" "import_resolution"
);
--> statement-breakpoint
CREATE TABLE "import_job_log_movie_watched_date" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_log_movie_watched_date_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_log_movie_id" bigint NOT NULL,
	"watched_date" date NOT NULL,
	"format" "watch_format_enum",
	"comment" text,
	"is_duplicate" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_job_log_tv_series" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_log_tv_series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_id" bigint NOT NULL,
	"raw_title" text NOT NULL,
	"raw_year" integer,
	"tv_series_id" bigint,
	"match_status" "import_match_status" DEFAULT 'unmatched' NOT NULL,
	"imported_rating" real,
	"imported_is_liked" boolean DEFAULT false NOT NULL,
	"imported_status" "log_tv_status",
	"existing_log_tv_series_id" bigint,
	"existing_rating" real,
	"existing_is_liked" boolean,
	"resolution" "import_resolution"
);
--> statement-breakpoint
CREATE TABLE "import_job_playlist" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_playlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_id" bigint NOT NULL,
	"title" text NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "import_job_playlist_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_playlist_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_playlist_id" bigint NOT NULL,
	"raw_title" text NOT NULL,
	"raw_year" integer,
	"type" "import_job_playlist_item_type" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	"match_status" "import_match_status" DEFAULT 'unmatched' NOT NULL,
	"source_order" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_job_review_movie" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_review_movie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_log_movie_id" bigint NOT NULL,
	"title" text,
	"body" text NOT NULL,
	"is_spoiler" boolean DEFAULT false NOT NULL,
	"existing_review_exists" boolean DEFAULT false NOT NULL,
	"resolution" "import_resolution"
);
--> statement-breakpoint
CREATE TABLE "import_job_review_tv_series" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_job_review_tv_series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"import_job_log_tv_series_id" bigint NOT NULL,
	"title" text,
	"body" text NOT NULL,
	"is_spoiler" boolean DEFAULT false NOT NULL,
	"existing_review_exists" boolean DEFAULT false NOT NULL,
	"resolution" "import_resolution"
);
--> statement-breakpoint
ALTER TABLE "import_job" ADD CONSTRAINT "import_job_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_bookmark" ADD CONSTRAINT "import_job_bookmark_import_job_id_import_job_id_fk" FOREIGN KEY ("import_job_id") REFERENCES "public"."import_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_bookmark" ADD CONSTRAINT "import_job_bookmark_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_bookmark" ADD CONSTRAINT "import_job_bookmark_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_movie" ADD CONSTRAINT "import_job_log_movie_import_job_id_import_job_id_fk" FOREIGN KEY ("import_job_id") REFERENCES "public"."import_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_movie" ADD CONSTRAINT "import_job_log_movie_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_movie" ADD CONSTRAINT "import_job_log_movie_existing_log_movie_id_log_movie_id_fk" FOREIGN KEY ("existing_log_movie_id") REFERENCES "public"."log_movie"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_movie_watched_date" ADD CONSTRAINT "import_job_log_movie_watched_date_import_job_log_movie_id_import_job_log_movie_id_fk" FOREIGN KEY ("import_job_log_movie_id") REFERENCES "public"."import_job_log_movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_tv_series" ADD CONSTRAINT "import_job_log_tv_series_import_job_id_import_job_id_fk" FOREIGN KEY ("import_job_id") REFERENCES "public"."import_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_tv_series" ADD CONSTRAINT "import_job_log_tv_series_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_log_tv_series" ADD CONSTRAINT "import_job_log_tv_series_existing_log_tv_series_id_log_tv_series_id_fk" FOREIGN KEY ("existing_log_tv_series_id") REFERENCES "public"."log_tv_series"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_playlist" ADD CONSTRAINT "import_job_playlist_import_job_id_import_job_id_fk" FOREIGN KEY ("import_job_id") REFERENCES "public"."import_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_playlist_item" ADD CONSTRAINT "import_job_playlist_item_import_job_playlist_id_import_job_playlist_id_fk" FOREIGN KEY ("import_job_playlist_id") REFERENCES "public"."import_job_playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_playlist_item" ADD CONSTRAINT "import_job_playlist_item_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_playlist_item" ADD CONSTRAINT "import_job_playlist_item_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_review_movie" ADD CONSTRAINT "import_job_review_movie_import_job_log_movie_id_import_job_log_movie_id_fk" FOREIGN KEY ("import_job_log_movie_id") REFERENCES "public"."import_job_log_movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_job_review_tv_series" ADD CONSTRAINT "import_job_review_tv_series_import_job_log_tv_series_id_import_job_log_tv_series_id_fk" FOREIGN KEY ("import_job_log_tv_series_id") REFERENCES "public"."import_job_log_tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_import_job_user_id" ON "import_job" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_status" ON "import_job" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_import_job_bookmark_import_job_id" ON "import_job_bookmark" USING btree ("import_job_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_bookmark_movie_id" ON "import_job_bookmark" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_bookmark_tv_series_id" ON "import_job_bookmark" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_log_movie_import_job_id" ON "import_job_log_movie" USING btree ("import_job_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_log_movie_movie_id" ON "import_job_log_movie" USING btree ("movie_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_log_movie_watched_date_log_movie_id" ON "import_job_log_movie_watched_date" USING btree ("import_job_log_movie_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_log_tv_series_import_job_id" ON "import_job_log_tv_series" USING btree ("import_job_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_log_tv_series_tv_series_id" ON "import_job_log_tv_series" USING btree ("tv_series_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_playlist_import_job_id" ON "import_job_playlist" USING btree ("import_job_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_playlist_item_playlist_id" ON "import_job_playlist_item" USING btree ("import_job_playlist_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_review_movie_log_movie_id" ON "import_job_review_movie" USING btree ("import_job_log_movie_id");--> statement-breakpoint
CREATE INDEX "idx_import_job_review_tv_series_log_tv_series_id" ON "import_job_review_tv_series" USING btree ("import_job_log_tv_series_id");