CREATE TABLE "provider" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provider_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"icon_light" text,
	"icon_dark" text,
	CONSTRAINT "provider_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
-- Nullable for now: 0065 backfills every row from the legacy provider/direction enum columns
-- (still present, untouched, below) before 0066 enforces NOT NULL / adds the PK.
ALTER TABLE "import_job" ADD COLUMN "provider_id" bigint;
--> statement-breakpoint
ALTER TABLE "import_source" ADD COLUMN "provider_id" bigint;
--> statement-breakpoint
ALTER TABLE "import_job" ADD CONSTRAINT "import_job_provider_id_provider_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."provider"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "import_source" ADD CONSTRAINT "import_source_provider_id_provider_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."provider"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
-- Dropping the old (provider, direction) composite PK now, ahead of 0066 adding provider_id as
-- the new PK, doesn't touch any data — this table is about to become import-only (see 0066),
-- so the old key's `direction` half wouldn't make sense as part of it going forward anyway.
ALTER TABLE "import_source" DROP CONSTRAINT "import_source_provider_direction_pk";
