CREATE TYPE "public"."pinned_item_type_enum" AS ENUM('movie', 'tv_series', 'playlist', 'person');--> statement-breakpoint
CREATE TABLE "pinned_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pinned_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"rank" varchar(255) NOT NULL,
	"type" "pinned_item_type_enum" NOT NULL,
	"movie_id" bigint,
	"tv_series_id" bigint,
	"playlist_id" bigint,
	"person_id" bigint,
	CONSTRAINT "check_pinned_item_type_references" CHECK ((
				(type = 'movie'::pinned_item_type_enum AND movie_id IS NOT NULL AND tv_series_id IS NULL AND playlist_id IS NULL AND person_id IS NULL)
				OR
				(type = 'tv_series'::pinned_item_type_enum AND tv_series_id IS NOT NULL AND movie_id IS NULL AND playlist_id IS NULL AND person_id IS NULL)
				OR
				(type = 'playlist'::pinned_item_type_enum AND playlist_id IS NOT NULL AND movie_id IS NULL AND tv_series_id IS NULL AND person_id IS NULL)
				OR
				(type = 'person'::pinned_item_type_enum AND person_id IS NOT NULL AND movie_id IS NULL AND tv_series_id IS NULL AND playlist_id IS NULL)
			))
);
--> statement-breakpoint
ALTER TABLE "pinned_item" ADD CONSTRAINT "pinned_item_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pinned_item" ADD CONSTRAINT "pinned_item_movie_id_movie_id_fk" FOREIGN KEY ("movie_id") REFERENCES "tmdb"."movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pinned_item" ADD CONSTRAINT "pinned_item_tv_series_id_tv_series_id_fk" FOREIGN KEY ("tv_series_id") REFERENCES "tmdb"."tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pinned_item" ADD CONSTRAINT "pinned_item_playlist_id_playlist_id_fk" FOREIGN KEY ("playlist_id") REFERENCES "public"."playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pinned_item" ADD CONSTRAINT "pinned_item_person_id_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "tmdb"."person"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_pinned_item_user_id" ON "pinned_item" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_pinned_item_rank" ON "pinned_item" USING btree ("rank");--> statement-breakpoint
CREATE INDEX "idx_pinned_item_type" ON "pinned_item" USING btree ("type");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_pinned_item_user_movie" ON "pinned_item" USING btree ("user_id","movie_id") WHERE "pinned_item"."type" = 'movie'::pinned_item_type_enum;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_pinned_item_user_tv_series" ON "pinned_item" USING btree ("user_id","tv_series_id") WHERE "pinned_item"."type" = 'tv_series'::pinned_item_type_enum;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_pinned_item_user_playlist" ON "pinned_item" USING btree ("user_id","playlist_id") WHERE "pinned_item"."type" = 'playlist'::pinned_item_type_enum;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_pinned_item_user_person" ON "pinned_item" USING btree ("user_id","person_id") WHERE "pinned_item"."type" = 'person'::pinned_item_type_enum;