CREATE TABLE "review_movie_comment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_movie_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"review_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"parent_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"body" text NOT NULL,
	"deleted_at" timestamp with time zone,
	"likes_count" bigint DEFAULT 0 NOT NULL,
	"replies_count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "check_review_movie_comment_body" CHECK ((length(body) >= 1) AND (length(body) <= 1000))
);
--> statement-breakpoint
CREATE TABLE "review_movie_comment_like" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_movie_comment_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"comment_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_review_movie_comment_like" UNIQUE("comment_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "review_tv_series_comment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_tv_series_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"review_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"parent_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"body" text NOT NULL,
	"deleted_at" timestamp with time zone,
	"likes_count" bigint DEFAULT 0 NOT NULL,
	"replies_count" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "check_review_tv_series_comment_body" CHECK ((length(body) >= 1) AND (length(body) <= 1000))
);
--> statement-breakpoint
CREATE TABLE "review_tv_series_comment_like" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_tv_series_comment_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"comment_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_review_tv_series_comment_like" UNIQUE("comment_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "review_movie_comment" ADD CONSTRAINT "review_movie_comment_review_id_review_movie_id_fk" FOREIGN KEY ("review_id") REFERENCES "public"."review_movie"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie_comment" ADD CONSTRAINT "review_movie_comment_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie_comment" ADD CONSTRAINT "review_movie_comment_parent_id_review_movie_comment_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."review_movie_comment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie_comment_like" ADD CONSTRAINT "review_movie_comment_like_comment_id_review_movie_comment_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."review_movie_comment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_movie_comment_like" ADD CONSTRAINT "review_movie_comment_like_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_comment" ADD CONSTRAINT "review_tv_series_comment_review_id_review_tv_series_id_fk" FOREIGN KEY ("review_id") REFERENCES "public"."review_tv_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_comment" ADD CONSTRAINT "review_tv_series_comment_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_comment" ADD CONSTRAINT "review_tv_series_comment_parent_id_review_tv_series_comment_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."review_tv_series_comment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_comment_like" ADD CONSTRAINT "review_tv_series_comment_like_comment_id_review_tv_series_comment_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."review_tv_series_comment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_tv_series_comment_like" ADD CONSTRAINT "review_tv_series_comment_like_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_review_movie_comment_review_id" ON "review_movie_comment" USING btree ("review_id");--> statement-breakpoint
CREATE INDEX "idx_review_movie_comment_parent_id" ON "review_movie_comment" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "idx_review_movie_comment_user_id" ON "review_movie_comment" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_review_movie_comment_created_at" ON "review_movie_comment" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_review_movie_comment_likes_count" ON "review_movie_comment" USING btree ("likes_count");--> statement-breakpoint
CREATE INDEX "idx_review_movie_comment_like_user_id" ON "review_movie_comment_like" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comment_review_id" ON "review_tv_series_comment" USING btree ("review_id");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comment_parent_id" ON "review_tv_series_comment" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comment_user_id" ON "review_tv_series_comment" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comment_created_at" ON "review_tv_series_comment" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comment_likes_count" ON "review_tv_series_comment" USING btree ("likes_count");--> statement-breakpoint
CREATE INDEX "idx_review_tv_series_comment_like_user_id" ON "review_tv_series_comment_like" USING btree ("user_id");