#!/bin/bash
set -e

PROTO_LIB_ROOT="./libs/protos"
PROTO_SRC_DIR="${PROTO_LIB_ROOT}/src/lib"
OUT_DIR="${PROTO_LIB_ROOT}/src/__generated__"
PROTOC_GEN_TS_PROTO_PATH="./node_modules/.bin/protoc-gen-ts_proto"

echo "🧹 Cleaning ${OUT_DIR}..."
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

echo "🚀 Generating TypeScript files..."

find "${PROTO_SRC_DIR}" -name "*.proto" | while read -r proto_file; do
  echo "Processing $proto_file..."
  
  REL_DIR=$(dirname "${proto_file}")
  REL_DIR=${REL_DIR#$PROTO_SRC_DIR/}
  
  if [[ "$REL_DIR" == "$PROTO_SRC_DIR" ]]; then
      REL_DIR=""
  fi

  mkdir -p "${OUT_DIR}/${REL_DIR}"

  protoc \
    --plugin="protoc-gen-ts_proto=${PROTOC_GEN_TS_PROTO_PATH}" \
    --ts_proto_out="${OUT_DIR}" \
    --ts_proto_opt=nestJs=true \
    --ts_proto_opt=useOptionals=messages \
    --ts_proto_opt=addGrpcMetadata=true \
    --ts_proto_opt=fileSuffix=.pb \
    --proto_path="${PROTO_SRC_DIR}" \
    "$proto_file"
done

echo "📦 Creating index.ts (Barrel file)..."

cd "${OUT_DIR}"
echo "// Auto-generated by scripts/proto-gen.sh" > "index.ts"

find . -name "*.ts" -not -name "index.ts" | while read -r file; do
  clean_path=${file#./}
  clean_path=${clean_path%.ts}
  
  echo "export * from './$clean_path';" >> "index.ts"
done

echo "✅ Done."