packages:
  - apps/*
  - libs/*

allowBuilds:
  nx: true
  '@nestjs/core': true
  '@firebase/util': true
  '@scarf/scarf': true
  bcrypt: true
  msgpackr-extract: true
  protobufjs: true
  '@parcel/watcher': true
  '@prisma/client': true
  'better-sqlite3': true
  esbuild: true
  sharp: true
  '@swc/core': true
  'unrs-resolver': true
