import fs from 'node:fs';
import path from 'node:path';

const ROOT_DIR = process.cwd();
const STATIC_DIR = path.join(ROOT_DIR, 'libs/assets/static');
const OUTPUT_DIR = path.join(ROOT_DIR, 'libs/assets/src/__generated__');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'manifest.ts');

type AssetTree = { [key: string]: AssetTree | string };

function toCamelCase(basename: string): string {
  return basename
    .replace(/\.[^/.]+$/, '')
    .replace(/[-_](.)/g, (_match, char: string) => char.toUpperCase());
}

function walk(dir: string, relPrefix: string): AssetTree {
  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => !entry.name.startsWith('.'))
    .sort((a, b) => a.name.localeCompare(b.name));

  const tree: AssetTree = {};

  for (const entry of entries) {
    const key = toCamelCase(entry.name);
    const relPath = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;

    tree[key] = entry.isDirectory() ? walk(path.join(dir, entry.name), relPath) : relPath;
  }

  return tree;
}

function render(tree: AssetTree, indent: number): string {
  const pad = ' '.repeat(indent);
  const lines = Object.entries(tree).map(([key, value]) => {
    const safeKey = JSON.stringify(key);
    if (typeof value === 'string') {
      return `${pad}${safeKey}: ${JSON.stringify(value)},`;
    }
    if (Object.keys(value).length === 0) {
      return `${pad}${safeKey}: {},`;
    }
    return `${pad}${safeKey}: {\n${render(value, indent + 2)}\n${pad}},`;
  });
  return lines.join('\n');
}

function run() {
  if (!fs.existsSync(STATIC_DIR)) {
    throw new Error(`Static assets folder not found: ${STATIC_DIR}`);
  }

  const tree = walk(STATIC_DIR, '');
  const body = render(tree, 2);

  const output = `// AUTO-GENERATED by \`nx run assets:generate\` from libs/assets/static/**
// Do not edit by hand, and do not commit this file (see libs/assets/.gitignore).

export const assetPaths = {
${body}
} as const;
`;

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output);

  console.log(`✅ Generated ${path.relative(ROOT_DIR, OUTPUT_FILE)}`);
}

run();
