#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Define directories
PROTO_DIR="./libs/shared/src/protos"
OUT_DIR="${PROTO_DIR}/__generated__"
PROTOC_GEN_TS_PROTO_PATH="./node_modules/.bin/protoc-gen-ts_proto"

echo "Clearing old generated files in ${OUT_DIR}..."
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

echo "Generating TypeScript from Protobuf files..."

# Use a glob pattern to find all .proto files
protoc \
  --plugin="protoc-gen-ts_proto=${PROTOC_GEN_TS_PROTO_PATH}" \
  --ts_proto_out="${OUT_DIR}" \
  --ts_proto_opt=nestJs=true \
  --ts_proto_opt=useOptionals=messages \
  --proto_path="${PROTO_DIR}" \
  ${PROTO_DIR}/*.proto

# Create a barrel file (index.ts) for easy imports from the generated directory
echo "Creating barrel file..."
echo "// Auto-generated by proto-gen.sh. Do not edit." > "${OUT_DIR}/index.ts"
find "${OUT_DIR}" -name "*.ts" -not -name "index.ts" | while read -r file; do
  filename=$(basename "$file" .ts)
  echo "export * from './${filename}';" >> "${OUT_DIR}/index.ts"
done

echo "Protobuf generation complete."
