name: CI Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: 🧪 Lint, Test & Build
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Skip for Release Please PRs
        if: ${{ startsWith(github.head_ref, 'release-please--branches') }}
        run: echo "Skipping CI for Release Please PRs."

      - name: ⬇️ Checkout Code
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 📦 Setup pnpm
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        uses: pnpm/action-setup@v6
        with:
          version: 11.25.0

      - name: 🔧 Setup Node.js
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: ⚙️ Install Dependencies
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        run: pnpm install --frozen-lockfile

      - name: 📝 Prepare Mock Env for CI
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        run: |
          cat <<EOF > apps/api/.env
          ASSETS_BASE_URL=http://localhost/assets
          S3_ENDPOINT=http://localhost
          S3_ACCESS_KEY_ID=mock
          S3_SECRET_ACCESS_KEY=mock
          TYPESENSE_HOST=localhost
          TYPESENSE_API_KEY=mock
          DATABASE_URL=postgres://localhost:5432/mock
          AUTH_SECRET=mock
          AUTH_GOOGLE_CLIENT_ID=mock
          AUTH_GOOGLE_IOS_CLIENT_ID=mock
          AUTH_GOOGLE_ANDROID_CLIENT_ID=mock
          AUTH_GOOGLE_CLIENT_SECRET=mock
          AUTH_GITHUB_CLIENT_ID=mock
          AUTH_GITHUB_CLIENT_SECRET=mock
          AUTH_FACEBOOK_CLIENT_ID=mock
          AUTH_FACEBOOK_CLIENT_SECRET=mock
          AUTH_APPLE_CLIENT_ID=mock
          AUTH_APPLE_TEAM_ID=mock
          AUTH_APPLE_KEY_ID=mock
          AUTH_APPLE_PRIVATE_KEY=mock
          AUTH_APPLE_BUNDLE_ID=mock
          REVENUECAT_API_KEY=mock
          REVENUECAT_WEBHOOK_SECRET=mock
          EOF

      - name: 🧠 Initialize Nx SHAs
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        uses: nrwl/nx-set-shas@v5

      - name: 🧹 Run Lint (Affected)
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        run: pnpm nx affected -t lint --parallel=3

      - name: 🧪 Run Tests (Affected)
        if: ${{ !startsWith(github.head_ref, 'release-please--branches') }}
        run: pnpm nx affected -t test --parallel=3
