name: PR Title Check

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    name: 📝 Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Verify Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            api
            web
            mobile
            notify
            worker
            deps
            repo
          requireScope: false
